env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parser: babel-eslint

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
    spread: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

rules:
  react/react-in-jsx-scope: off

settings:
  react:
    version: '16'

globals:
  React: true
  PropTypes: true